---
title: "Exercises I"
author: David Zimmermann
date: 20-09-2016
output: html_document
---
# Exercises

1. Load and get familiar with the data, tidy the data and save it in a clean format.
2. Visualise prices for selected stocks (level and indexed) and save the output as pdfs.
3. Compute returns for all stocks, visualise correlations between different selected stocks.

# 0) File System:
```{r files}
list.files(full.names = T, recursive = T)
```

# 1) Data Munging and Tidying

```{r mungeAndTidy, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(tidyr)

# setwd("..") # if necessary, change working directory

df <- read_csv("data/stockData.csv")

names(df)
dim(df)
summary(df)

# leave out V
df <- df %>% select(-V)

# have a look at the data again
df %>% head

df_long <- gather(df, key = ticker, value = price, -date)
head(df_long)

# save the tidy data
write_csv(df_long, "data/tidyStockData.csv")
```

# 2) Data Vis 1

```{r visOne, message=FALSE, warning=FALSE}
library(ggplot2)
library(RColorBrewer)

# setwd("..") # if necessary, change working directory

df <- read_csv("data/tidyStockData.csv")
df <- df %>% mutate(date = as.Date(date))

# 1 Filter selected Stocks
ticker_selection <- c("GS", "JPM", "AXP")
df_selection <- df %>% filter(ticker %in% ticker_selection)

# 2 Compute indexed prices
df_selection <- df_selection %>% group_by(ticker) %>% 
  mutate(price_index = (price / price[1]) * 100)

# 3 A) Visualise Prices
plot_prices <- ggplot(df_selection, aes(x = date, y = price, color = ticker)) +
  geom_line() + 
  labs(x = "Time", y = "Price in USD", 
       title = "Price Developments for Selected Financial Stocks") + 
  scale_color_manual(name = "Ticker", 
                     values = brewer.pal(length(ticker_selection), "Set1")) + 
  theme_minimal()

plot_prices # show plot

ggsave("prices.pdf", plot_prices)

# 3 B) Visualise Indexed Prices
plot_idx_prices <- ggplot(df_selection, aes(x = date, y = price_index, 
                                            color = ticker)) +
  geom_line() + 
  labs(x = "Time", y = "Price Index\n(01-01-2000 = 100)", 
       title = "Price Developments for Selected Financial Stocks (Indexed)") + 
  scale_color_manual(name = "Ticker", 
                     values = brewer.pal(length(ticker_selection), "Set1")) + 
  theme_minimal()

plot_idx_prices # show plot

ggsave("price_index.pdf", plot_idx_prices)
```

# 3) Data Vis 2

```{r visTwo, message=FALSE, warning=FALSE}
library(RColorBrewer)
library(scales) # for percent axis

# setwd("..") # if necessary, change working directory

df <- read_csv("data/tidyStockData.csv")
df <- df %>% mutate(date = as.Date(date))

# 1 Compute returns
df <- df %>% group_by(ticker) %>% mutate(ret = price / lag(price) - 1)

df_selection <- df %>% filter(ticker %in% c("GS", "JPM"))

df_selection_wide <- spread(df_selection %>% select(date, ticker, ret), 
                            key = ticker, value = ret)

# 2 Compute Correlations
cor(df_selection_wide %>% na.omit %>% select(GS, JPM))

# 3 Visualise Correlations
plot_cor <- ggplot(df_selection_wide, aes(x = GS, y = JPM)) + 
  geom_abline(slope = 1, intercept = 0, color = "#67001f", size = 0.1) +
  geom_point(shape = 3, alpha = 0.3) + 
  geom_rug(alpha = 0.2) + 
  scale_x_continuous(labels = percent) + 
  scale_y_continuous(labels = percent) + 
  labs(x = "Goldman Sachs", y = "JPMorgan Chase", 
       title = "Correlations of Returns") + 
  theme_minimal()

plot_cor # show plot

ggsave("plot_correlation.pdf", plot_cor)

```
